spring.application.name=MTG_APPARIEMENT_BIS

# SPRING DATA JPA
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCL
spring.datasource.username=MTG
spring.datasource.password=MagicApp#0112
spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update 

#SPRING WEB
server.servlet.context-path=/mtg

# SPRING SECURITY
spring.main.allow-circular-references=true 